version: '3.8'

services:
  sum-service:
    build: ./sum
    container_name: sum_container
    ports:
      - "5001:5000"
    restart: unless-stopped

  sub-service:
    build: ./sub
    container_name: sub_container
    ports:
      - "5002:5000"
    restart: unless-stopped

  mul-service:
    build: ./mul
    container_name: mul_container
    ports:
      - "5003:5000"
    restart: unless-stopped

  div-service:
    build: ./div
    container_name: div_container
    ports:
      - "5004:5000"
    restart: unless-stopped

  app-service:
    build: ./app
    container_name: app_container
    ports:
      - "5005:5000"
    depends_on:
      - sum-service
      - sub-service
      - mul-service
      - div-service
    restart: unless-stopped
