version: '3.8'

services:
  sum-service:
    build: ./sum
    container_name: sum_container
    ports:
      - "5001:5000"
    restart: unless-stopped

  sub-service:
    build: ./sub
    container_name: sub_container
    ports:
      - "5002:5000"
    restart: unless-stopped

  mul-service:
    build: ./mul
    container_name: mul_container
    ports:
      - "5003:5000"
    restart: unless-stopped

  div-service:
    build: ./div
    container_name: div_container
    ports:
      - "5004:5000"
    restart: unless-stopped
