apiVersion: apps/v1
kind: Deployment
metadata:
  name: div-service
  labels:
    app: div-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: div-service
  template:
    metadata:
      labels:
        app: div-service
    spec:
      containers:
        - name: div-service
          image: joaomacas02/div-service:latest  # Ensure this image exists
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: div-service
spec:
  selector:
    app: div-service
  ports:
    - protocol: TCP
      port: 5004
      targetPort: 5000
