apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: db_writer 
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: db123  
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db  # MongoDB data will be stored here
        - name: mongo-init-script
          mountPath: /docker-entrypoint-initdb.d/  # Init scripts will be loaded from here
      volumes:
      - name: mongo-data
        hostPath:
          path: /home/vagrant/data  # Host path where MongoDB data will be saved
      - name: mongo-init-script
        configMap:
          name: mongo-init-script
--- 
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
