apiVersion: apps/v1
kind: Deployment
metadata:
  name: mul-service
  labels:
    app: mul-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mul-service
  template:
    metadata:
      labels:
        app: mul-service
    spec:
      containers:
        - name: mul-service
          image: joaomacas02/mul-service:latest  # Ensure this image exists
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: mul-service
spec:
  selector:
    app: mul-service
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5000
