apiVersion: apps/v1
kind: Deployment
metadata:
  name: sub-service
  labels:
    app: sub-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sub-service
  template:
    metadata:
      labels:
        app: sub-service
    spec:
      containers:
        - name: sub-service
          image: joaomacas02/sub-service:latest  # Ensure this image exists
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: sub-service
spec:
  selector:
    app: sub-service
  ports:
    - protocol: TCP
      port: 5002 # VM PORT 
      targetPort: 5000 # CONTAINER PORT
