apiVersion: apps/v1
kind: Deployment
metadata:
  name: sum-service
  labels:
    app: sum-service
spec:
  replicas: 1  # Number of pod replicas
  selector:
    matchLabels:
      app: sum-service
  template:
    metadata:
      labels:
        app: sum-service
    spec:
      containers:
        - name: sum-service
          image: joaomacas02/sum-service:latest
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "200m" 
---
apiVersion: v1
kind: Service
metadata:
  name: sum-service
spec:
  selector:
    app: sum-service
  ports:
    - protocol: TCP
      port: 5001  # External port to expose
      targetPort: 5000  # Port inside the container

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sum-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sum-service
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
