---
- hosts: master
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Copy sum-pod pod file from Ansible host to the master node
      copy: 
        src: ./kube_pods/sum-pod.yaml
        dest: /home/ubuntu/sum-pod.yaml
        mode: '0777'

    - name: Start deployment of sum-pod
      shell: sudo kubectl apply -f /home/ubuntu/sum-pod.yaml

    - name: Copy div-pod pod file from Ansible host to the master node
      copy: 
        src: ./kube_pods/div-pod.yaml
        dest: /home/ubuntu/div-pod.yaml
        mode: '0777'

    - name: Start deployment of div-pod
      shell: sudo kubectl apply -f /home/ubuntu/div-pod.yaml

    - name: Copy calculator-app-pod pod file from Ansible host to the master node
      copy: 
        src: ./kube_pods/calculator-app-pod.yaml
        dest: /home/ubuntu/calculator-app-pod.yaml
        mode: '0777'

    - name: Start deployment of calculator-app-pod
      shell: sudo kubectl apply -f /home/ubuntu/calculator-app-pod.yaml