---
- hosts: master
  become: yes
  become_user: root
  become_method: sudo
  tasks:   
    - name: Delete sum-pod deployment
      shell: sudo kubectl delete pod sum-pod
    - name: Delete div-pod deployment
      shell: sudo kubectl delete pod div-pod
    - name: Delete calculator-app-pod deployment
      shell: sudo kubectl delete pod calculator-app-pod