---
- hosts: master
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Create a folder for MongoDB data
      file:
        path: /home/vagrant/data
        state: directory
        mode: '0777'

    - name: Copy the entire kube directory to the master node
      copy:
        src: ./kube/
        dest: /home/ubuntu/kube/
        mode: '0777'
        remote_src: no

    - name: Start deployment of ConfigMap
      shell: sudo kubectl apply -f /home/ubuntu/kube/configmap.yaml

    - name: Start deployment of MongoDB
      shell: sudo kubectl apply -f /home/ubuntu/kube/mongo.yaml

    - name: Start deployment of sum-service
      shell: sudo kubectl apply -f /home/ubuntu/kube/sum-service.yaml

    - name: Start deployment of sub-service
      shell: sudo kubectl apply -f /home/ubuntu/kube/sub-service.yaml

    - name: Start deployment of mul-service
      shell: sudo kubectl apply -f /home/ubuntu/kube/mul-service.yaml

    - name: Start deployment of div-service
      shell: sudo kubectl apply -f /home/ubuntu/kube/div-service.yaml

    - name: Start deployment of calculator-app-service
      shell: sudo kubectl apply -f /home/ubuntu/kube/calculator-app-service.yaml

    - name: Start deployment of db-service
      shell: sudo kubectl apply -f /home/ubuntu/kube/db-service.yaml

    - name: Initialize the monitoring services
      shell: |
        sudo helm upgrade --install --namespace monitoring --create-namespace --atomic --debug --timeout 300s prometheus-stack prometheus-community/kube-prometheus-stack

    - name: Start deployment of monitoring-service
      shell: sudo kubectl apply -f /home/ubuntu/kube/monitoring-service.yaml

    - name: Start deployment of metrics-server
      shell: sudo kubectl apply -f /home/ubuntu/kube/metrics-server.yaml

    - name: Retrieve master node IP address
      set_fact:
        master_ip: "{{ hostvars['master'].ansible_host }}"

    - name: Print Server IP and Port for services
      debug:
        msg: "Access Calculator Website: at: http://{{ master_ip }}:30100"

    - name: Print Grafana URL
      debug:
        msg: "Access Grafana at: http://{{ master_ip }}:30101"

    - name: Print Grafana User and Password
      debug:
        msg: "user: admin password: prom-operator"
